name: Publish Docker image

on:
  push:
    branches: ["master", "main"]

env:
  AR_REGION: ${{ secrets.AR_REGION }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  AR_REPO: ${{ secrets.AR_REPO }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up gcloud auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.AR_REGION }}-docker.pkg.dev -q

      - name: Build and push
        run: |
          TAG=${GITHUB_SHA::7}
          IMAGE=${AR_REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/${AR_REPO}/namesite:${TAG}
          docker build -t ${IMAGE} .
          docker push ${IMAGE}

# Required GitHub Secrets:
# - GCP_SA_KEY (JSON key for Artifact Registry pusher, not base64)
# - GCP_PROJECT_ID (e.g., my-gcp-project)
# - AR_REGION (e.g., us)
# - AR_REPO (e.g., web)

